## Day 20: Particle Swarm
    
http://adventofcode.com/2017/day/20

### Part 1

The answer here is the particle with the smallest acceleration magnitude. If two particles with different accelerations start from completely arbitrary finite locations and velocities, then at some point the particle with the higher acceleration will have higher velocity and continue to have higher velocity, so then at some possibly later point will be diverging further and faster from the origin. 

The input format is a bit awkward, so I've used Emacs to turn it into csv.

In [1]:
import numpy as np

def split_by_length(xs, length):
    l_xs = list(xs)
    return [l_xs[i:i+length] for i in range(0, len(l_xs), length)]

        
with open('input.csv') as f:
    particles = [np.array(v) for v in [split_by_length(map(int, line.strip().split(',')), 3) 
                                       for line in f]]
    
particles[0]

array([[ -717, -4557,  2578],
       [  153,    21,    30],
       [   -8,     8,    -7]])

Using Manhattan vectors is a bit odd, but I can't see why it wouldn't work for this. The particle having acceleration with the largest Manhattan magnitude will still move further away than others when using Manhattan distance as a measure of distance.

In [2]:
def manhattan_magnitude(v):
    return sum(abs(v_i) for v_i in v)

def acceleration_magnitude(p):
    return manhattan_magnitude(p[2])

acceleration_magnitude(particles[0])

23

In [3]:
min(range(len(particles)), key=lambda i: acceleration_magnitude(particles[i]))

115

In [4]:
particles[115]

array([[-129, 1190, -665],
       [   3,  -82,   41],
       [   1,    0,    1]])

That looks small, let's give it a go.

It's the wrong answer. What am I missing? 

In [5]:
for p in sorted(particles, key=acceleration_magnitude)[:10]:
    print(p)

[[-129 1190 -665]
 [   3  -82   41]
 [   1    0    1]]
[[  528 -1788 -1536]
 [    3    77    65]
 [   -2     0     0]]
[[  692  -175 -1125]
 [  -38    19    49]
 [    0    -1     1]]
[[  409   864 -1345]
 [    1   -28    32]
 [   -1     0     1]]
[[-1085  -561  1531]
 [   41    -8   -56]
 [    0     2     0]]
[[1119 -358 -696]
 [ -83   20   46]
 [   2    0   -1]]
[[-940 1847 1177]
 [  45  -71  -30]
 [   0   -1   -2]]
[[ 1720   726 -1414]
 [  -33   -28    64]
 [   -2     0    -1]]
[[ -932   143 -1423]
 [   50   -10   107]
 [    1     0    -2]]
[[-2370  3605   -22]
 [   91  -112    15]
 [    0    -2    -1]]


Of course, I need to distinguish between particles with the same acceleration. For two particles with the same acceleration one with a velocity that minimises the disruption to the acceleration will travel furthest. This can be measured by the magnitude of the acceleration added to the original velocity.

<i>Slightly</i> more formally, if $p_t$ is the position at time zero, $v_t$ the velocity, and $a$ the constant acceleration, then
\begin{array}{lllll}
p_0 & = & p_0 & \\
p_1 & = & p_0 + (v_0 + a) & = & p_0 + v_0 + a \\
p_2 & = & p_0 + (v_0 + a) + (v_0 + 2a) & = & p_0 + 2v_0 + 3a \\
p_3 & = & p_0 + (v_0 + a) + (v_0 + 2a) & = & p_0 + 3v_0 + 6a \\
& \vdots \\
p_t & = & p_0 + t.v_0 + \frac{t(t+1)}{2}a
\end{array}
The coefficient of $a$ is $\frac{t+1}{2}$ larger than that of $v_0$, so as $t$ becomes sufficiently large the acceleration value dominates, however small it is, and the initial velocity determines which will have travelled further amongst particles with equal acceleration. 

In [6]:
def velocity_magnitude(p):
    return manhattan_magnitude(p[1])

min(range(len(particles)), 
    key= lambda i: (acceleration_magnitude(particles[i]), 
                    manhattan_magnitude(particles[i][2] + particles[i][1])))

344

In [7]:
particles[344]

array([[  409,   864, -1345],
       [    1,   -28,    32],
       [   -1,     0,     1]])

That's the right answer.

### Part 2

For each pair of particles find a positive integer $t$ such that
$$ p_{i0} + t.v_{i0} + \frac{t(t+1)}{2}a_i = p_{j1} + t.v_{j1} + \frac{t(t+1)}{2}a_j $$

I'm not sure I'll have time for this today.